### PR TITLE
Update to indigo 0.1.0

### PR DESCRIPTION
**Pull request by alexppxela**
- Update to tendermint 0.11.1
- Add scripts to ease several tests launches

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-performance-test/2)

### CODE REVIEW

**Comment by such** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[ansible/roles/indigo/tasks/main.yml, line 57 at r1](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-KyMPYauMydNXzraaxBX:-KyMPYauMydNXzraaxBY:bvchbkw) ([raw file](https://github.com/stratumn/indigo-performance-test/blob/4cc6b655366c283e81d3b27b0ffd3d8f33d01f8f/ansible/roles/indigo/tasks/main.yml#L57)):*
> ```YAML
> #     path: "{{ tendermint_dir }}/data"
> #     state: absent
> #     seuser: root
> ```

it might be better to uncomment this and add a guard or a tag or something...

---

*[ansible/roles/indigo/templates/docker-compose.yml.j2, line 18 at r1](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-KyMPGGKL29Va1fYzKkO:-KyMPGGLA18-ghef8ZKp:b-ijq40j) ([raw file](https://github.com/stratumn/indigo-performance-test/blob/4cc6b655366c283e81d3b27b0ffd3d8f33d01f8f/ansible/roles/indigo/templates/docker-compose.yml.j2#L18)):*
> ```
>     - store
>   store:
>     image: alexppxela/tmstore:latest
> ```

it should work with stratumn/tmstore:0.1.0 ?

---

*[ansible/roles/indigo/templates/docker-compose.yml.j2, line 31 at r1](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-KyMPMLYzeTbxKekzfq8:-KyMPMLYzeTbxKekzfq9:b-2guby3) ([raw file](https://github.com/stratumn/indigo-performance-test/blob/4cc6b655366c283e81d3b27b0ffd3d8f33d01f8f/ansible/roles/indigo/templates/docker-compose.yml.j2#L31)):*
> ```
>     command: [dummytmpop, -home, /data/tendermint, -rules_filename, "", -unsafe]
>     # image: alexppxela/tmdummy:latest
>     # command: [tmdummy, -unsafe]
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2)*

**Comment by alexppxela** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[ansible/roles/indigo/tasks/main.yml, line 57 at r1](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-KyMPYauMydNXzraaxBX:-KyPguEzzCfmiF7LqHia:b-y3vlpk) ([raw file](https://github.com/stratumn/indigo-performance-test/blob/4cc6b655366c283e81d3b27b0ffd3d8f33d01f8f/ansible/roles/indigo/tasks/main.yml#L57)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

it might be better to uncomment this and add a guard or a tag or something...
</blockquote></details>

Or delete this comment because usually, we do not reinstall indigo.
I'll remove this (the second way is beautifuler but does not work, I didn't investigate why)

---

*[ansible/roles/indigo/templates/docker-compose.yml.j2, line 18 at r1](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-KyMPGGKL29Va1fYzKkO:-KyPh0ZTW-k_PDAQYMV1:b-c4y54b) ([raw file](https://github.com/stratumn/indigo-performance-test/blob/4cc6b655366c283e81d3b27b0ffd3d8f33d01f8f/ansible/roles/indigo/templates/docker-compose.yml.j2#L18)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

it should work with stratumn/tmstore:0.1.0 ?
</blockquote></details>

There is the random bug about asynchronous flush in WAL file. We need to release a newest version using tendermint 0.11.1.
You are true, it must be an official stratumn version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2)*

**Comment by such** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-:-KyQAwin2U9X8KUpp3XD:bnfp4nl)*

**Comment by such** [comment]
Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-performance-test/2#-:-Ky_cuwOS4xYcqyjAqwI:bnfp4nl)*

**Pull request merged**
